(* ========================================================================= *)
(* Vectors encoded as binary tree dependently typed on the binary            *)
(* representation of finite types.                                           *)
(*                                                                           *)
(* (c) Copyright, Andrea Gabrielli, Marco Maggesi 2017-2018                  *)
(* (c) Copyright, Marco Maggesi 2025                                         *)
(* ========================================================================= *)

loadt "BinTreeVec/binary.ml";;      (* Computing with binary expansions     *)
loadt "BinTreeVec/vector0.ml";;     (* Zero-based vectors                   *)
loadt "BinTreeVec/btvectors.ml";;   (* Binary tree vectors                  *)
